server:
  port: 8001
spring:
  main:
    banner-mode: 'off'
  application:
    name: Eureka-Server-One

eureka:
  client:
    serviceUrl:
     defaultZone: http://127.0.0.1:8002/eureka/
  instance:
    prefer-ip-address: true # 可以使用IP地址来标注注册中心地址 也可以直接加 单引号
